# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-13 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_seasons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=50, verbose_name='Series name')),
                ('url', models.URLField(verbose_name='Url video')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
                ('season_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Seasons')),
            ],
        ),
    ]
